# Generated by Django 5.1.6 on 2025-04-19 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('h_i', models.BooleanField(verbose_name='¿Presente?')),
                ('hora_inicio', models.TimeField(auto_now_add=True)),
                ('h_s', models.BooleanField(default=False, verbose_name='¿Presente?')),
                ('hora_salida', models.TimeField(auto_now=True, null=True)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
            },
        ),
    ]
