# Generated by Django 5.2.1 on 2025-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='h_i',
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='h_s',
        ),
        migrations.AddField(
            model_name='assistance',
            name='Asis',
            field=models.BooleanField(default=False, verbose_name='Asistente'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
    ]
