# Generated by Django 5.2.1 on 2025-06-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_remove_assistance_h_i_remove_assistance_h_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodos', models.CharField(max_length=50, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.AddField(
            model_name='assistance',
            name='id_periodo',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='asistencia.periodo'),
            preserve_default=False,
        ),
    ]
