# Generated by Django 5.2.1 on 2025-06-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='Usuario.jpg', max_length=250, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
    ]
