# Generated by Django 5.2.1 on 2025-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(default='light', max_length=50, verbose_name='Theme'),
        ),
    ]
