# Generated by Django 5.2.1 on 2025-07-02 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_horarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='Dia',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes')], max_length=50, verbose_name='Dias'),
        ),
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('id_User', 'id_fecha')},
        ),
    ]
