# Generated by Django 5.2.1 on 2025-07-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_horarios_dia_alter_assistance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='Dia',
            field=models.CharField(max_length=50, verbose_name='Dias'),
        ),
    ]
