# Generated by Django 5.2.1 on 2025-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_horarios_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
