# Generated by Django 5.2.1 on 2025-07-04 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_alter_assistance_hora_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='id_fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.fecha', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.periodo', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=50, verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Hora_E',
            field=models.TimeField(verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='Hora_S',
            field=models.TimeField(verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
