# Generated by Django 5.2.1 on 2025-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_assistance_id_user_alter_assistance_id_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='Dia',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miercoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes')], max_length=50, verbose_name='Dias'),
        ),
    ]
