# Generated by Django 5.1.6 on 2025-03-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='asis',
            field=models.BooleanField(verbose_name='¿Presente?'),
        ),
    ]
