# Generated by Django 5.1.6 on 2025-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_assistance_asis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'verbose_name': 'asistencia', 'verbose_name_plural': 'asistencias'},
        ),
        migrations.AlterField(
            model_name='assistance',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True, verbose_name='hora de entrada'),
        ),
    ]
