# Generated by Django 5.1.6 on 2025-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_assistance_options_alter_assistance_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='hora_salida',
            field=models.TimeField(null=True, verbose_name='fecha de salida'),
        ),
    ]
