# Generated by Django 5.1.6 on 2025-04-09 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_assistance_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='hora_inicio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='hora_salida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
