# Generated by Django 5.1.6 on 2025-04-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_assistance_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='hora_inicio',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='hora_salida',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
