# Generated by Django 5.1.6 on 2025-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_alter_assistance_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='asis',
            new_name='h_i',
        ),
        migrations.AlterField(
            model_name='assistance',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='fecha'),
        ),
    ]
