# Generated by Django 5.1.6 on 2025-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_rename_asis_assistance_h_i_alter_assistance_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='h_s',
            field=models.BooleanField(default=False, verbose_name='¿Presente?'),
        ),
    ]
